# Generated by Django 4.1.3 on 2022-11-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категроии',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название мероприятия')),
                ('data_begin', models.DateTimeField(verbose_name='Начало мероприятия')),
                ('data_end', models.DateTimeField(verbose_name='Конец мероприятия')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.category', verbose_name='Категория')),
            ],
        ),
    ]
