# Generated by Django 4.1.3 on 2022-11-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['name'], 'verbose_name': 'Мероприятия', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
